### PR TITLE
[WIP] General Metadata for MTF

### PR DESCRIPTION
**Pull request by jscotka**
initial draft for general metadata what can be used by MTF

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Wow, so there is no industry standard for doing this yet?

**Comment by jscotka** [comment]
I was not able to find something :-) what is directly in python. There exist some symbolic formula parser, but it has complex dependency. If you find something I'll be glad :-)

**Comment by TomasTomecek** [comment]
@jscotka You are the quality expert here.

**Comment by jscotka** [comment]
it is replaced by 
https://github.com/fedora-modularity/meta-test-family/pull/165

**Pull request closed without merging**
