### PR TITLE
systemd-run backward compotibility (without wait option)

### PR DESCRIPTION
**Pull request by jscotka**
experimental support for systemd-run without --wait option

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
why do we need such hacks in new code?

**Comment by jscotka** [comment]
@ignatenkobrain because Fedora-25 and lower versions of fedora and RedHat Enterprise Linux 7 / CentOS7
and also in taskotron production instance, default fedora version now is Fedora-25 (what caused issues for MTF automation)

But I have to do comprehensive testing of this feature. it is not intended for merging now. But comments are welcomed.

**Comment by ignatenkobrain** [comment]
@jscotka f25 will become EOL in few months. talking about EL7, I would recommend you to request backporting feature on RHBZ rather than making workaround.

**Comment by jscotka** [comment]
@ignatenkobrain yep, it would be better. But there is several issues:

* It will took long time to backport these options to EL7 (it is low priority, in case just me needs it)
* If nobody else  is interested in this option in EL7 it will be never fixed.

So this workaround is fast solution what will fix it  in few days instead of months or years or never. But I agree that fix the root cause sould be the best.

Otherwise I've used machinectl shell (in previous versions of MTF what was in better in some handling and working in F25 and EL-7) but it caused very ugly side-effects and I've filled more upstream bugs like (in shortcut machinectl shell is not intended to use it noniteractively :-) :
* https://github.com/systemd/systemd/issues/5879
* https://github.com/systemd/systemd/issues/5878

**Pull request merged**
