### PR TITLE
Implement class used only for testing. W/o docker and similar engine.

### LINKED ISSUE #16: running mtf in a container results in odd traceback
```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:576
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1121, in setUp
    return self.backend.setUp()
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 286, in setUp
    self.__prepareContainer()
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 321, in __prepareContainer
    service_manager = service.ServiceManager()
  File "/usr/lib/python2.7/site-packages/avocado/utils/service.py", line 774, in service_manager
    internal_service_manager = _service_managers[get_name_of_init(run)]
KeyError: 'make'
```

code from [here](https://github.com/container-images/container-image-template/pull/32)

### PR DESCRIPTION
**Pull request by phracek**
This Pull Request implements a functionality like running only tests without starting docker engine, nspawn or rpm based repositories.

For setting and start only tests, just write MODULE=only_tests. I would be glad for any kind of feedback.
Just let me know.
This issues fixes #16

### CODE REVIEW

**Comment by TomasTomecek** [comment]
I'm not able to perform a code review, since I'm not familiar with the codebase. Let me just give it a go.

**Comment by TomasTomecek** [comment]
I pushed one more commit to this branch which bumps the version of mtf so I was able to install it in my container. I ran the test suite from https://github.com/container-images/container-image-template/pull/32

Unfortunately, it crashed:

```
Not logging /proc/pci (file does not exist)
Not logging /sys/kernel/debug/sched_features (file does not exist)
Commands configured by file: /etc/avocado/sysinfo/commands
Files configured by file: /etc/avocado/sysinfo/files
Profilers configured by file: /etc/avocado/sysinfo/profilers
Profiler disabled
System log file not found (looked for ['/var/log/messages', '/var/log/syslog', '/var/log/system.log'])
Journalctl collection failed: No JSON object could be decoded
PARAMS (key=timeout, path=*, default=None) => None
START 01-sanity1.py:SanityCheck1.test1
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/avocado/core/runner.py", line 325, in _run_test
    instance = loader.load_test(test_factory)
  File "/usr/lib/python2.7/site-packages/avocado/core/loader.py", line 338, in load_test
    test_instance = test_class(**test_parameters)
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1231, in __init__
    (self.backend, self.moduleType) = get_backend()
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1507, in get_backend
    return OnlyTestsHelper(), amodule
  File "/usr/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1091, in __init__
    self.info = self.config['module']['only_tests']
KeyError: 'only_tests'

Avocado crashed: TestError: Process died before it pushed early test_status.
Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

**Comment by phracek** [comment]
I see, this is not documented yet. config.yaml has three dict possibilities: docker (https://pagure.io/modularity-testing-framework/blob/master/f/examples/memcached/config.yaml#_15) , rpm (https://pagure.io/modularity-testing-framework/blob/master/f/examples/memcached/config.yaml#_22) and newly only_tests
I don't want to mix rpm dictionary and only_tests dictionary. 

Unfortunately, I did not update an example and even documentation. Will do it soon. In next commit.

Thanks for test, though.

**Comment by phracek** [comment]
In container-image-template repo I did this change:

~~~
diff --git a/x.y/tests/config.yaml b/x.y/tests/config.yaml
index d4910d3..e34ab1a 100644
--- a/x.y/tests/config.yaml
+++ b/x.y/tests/config.yaml
@@ -77,9 +77,11 @@ module:
         setup: echo Do magic with general config stored on host;
                echo More magic
         cleanup: echo Cleanup magic
-        start: /bin/true
-        stop: /bin/true
-        status: /bin/true
+        #start: /bin/true
+        #stop: /bin/true
+        #status: /bin/true
+    only_tests:
+        setup: echo Do magic with general config stored on host;
 # link to repo (additiona repos are added via dependencies in moduleMD file), in case you will
 # use "compose", this will be ignored
 # env var: URL

~~~

**Comment by phracek** [comment]
Issue was solved by PR #44

**Pull request closed without merging**
