### PR TITLE
PR to test Jenkins CI - no merging

### PR DESCRIPTION
**Pull request by psklenar**
Hello,
this is only testing pull request - I am trying start CI on pull request.

Dont merge. I will delete it after that

idea:
1, pull request [DONE]
2, jenkins start tests [DONE]
3, jenkins notify github [DENIED]
   our jenkinks cannot be updated by any plugins ...
   there is some script which could do that, but it doesn't work for unknown reason (i didnt invest no time here)

### CODE REVIEW

**Comment by psklenar** [comment]
cool,
CI starts working, now I am trying to found how to report results into this commnets here

**Comment by alexxa** [comment]
@psklenar Hmm.. Will it be the same if to experiment on a fork of this repo? If not, if possible update the title to smth like: PR to test Jenkins CI - no merging. Thanks.

**Comment by alexxa** [comment]
@psklenar I'm asking because with every commit to this PR, all of those who watch this repo will get an email notification.

**Comment by psklenar** [comment]
to @alexxa 
I cannot test it via my local fork repo, than I will be not sure about right variable.
I chnaged title as you suggested, hope its ok.

**Comment by alexxa** [comment]
@psklenar ack, thanks.

**Comment by jscotka** [comment]
Can be closed

**Pull request closed without merging**
