### PR TITLE
Revert "Tests whether dnf contains --nodocs and clean all"

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reverts fedora-modularity/meta-test-family#20

It is not complete and doesn't do right job (see original PR for comments).

### CODE REVIEW

**Comment by phracek** [comment]
You are saying in PR what is wrong. That's fine, but related to getting yum/dnf I don't see right way. Only this is not correct. What is correct approach?

The same for `dnf clean all` or `yum clean all`

Regarding documents. I am checking whether package is really installed in container and If so, then I check whether it really does not contain document.

If this is wrong, let's fix it and not revert PR.

**Comment by ignatenkobrain** [comment]
@phracek why did we merge PR in first place even I requested changes there?

**Comment by jscotka** [comment]
Otherwise @ignatenkobrain @phracek . 
please use {GUESTPACKAGER} inside the command, every run command is formated by using https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/common.py#L347 trans_dict from https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/common.py#L58
what sets what packager to use, yum, dnf, apt, etc,
Implementation is not perfect, but at least it is good to have it on one place, how to decide what command to use.

**Comment by phracek** [comment]
accidentally I remove the code. I will file a new PR.

**Pull request closed without merging**
